//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestImageStreamTagImport) DeepCopyInto(out *TestImageStreamTagImport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestImageStreamTagImport.
func (in *TestImageStreamTagImport) DeepCopy() *TestImageStreamTagImport {
	if in == nil {
		return nil
	}
	out := new(TestImageStreamTagImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestImageStreamTagImport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestImageStreamTagImportList) DeepCopyInto(out *TestImageStreamTagImportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TestImageStreamTagImport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestImageStreamTagImportList.
func (in *TestImageStreamTagImportList) DeepCopy() *TestImageStreamTagImportList {
	if in == nil {
		return nil
	}
	out := new(TestImageStreamTagImportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestImageStreamTagImportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestImageStreamTagImportSpec) DeepCopyInto(out *TestImageStreamTagImportSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestImageStreamTagImportSpec.
func (in *TestImageStreamTagImportSpec) DeepCopy() *TestImageStreamTagImportSpec {
	if in == nil {
		return nil
	}
	out := new(TestImageStreamTagImportSpec)
	in.DeepCopyInto(out)
	return out
}
