run:
  timeout: 10m

linters:
  enable:
    - unused
    - gosimple
    - gofmt
    - govet
    - staticcheck
    - unparam
    - unconvert
    - errcheck
    - ineffassign
    - misspell
    - bodyclose
    - errorlint
  disable-all: true

linters-settings:
  errorlint:
    errorf: true
    errorf-multi: false
    asserts: false
    comparison: false

issues:
  exclude-rules:
  - linters:
    - unparam
    text: \(\*leaseStep\)\.Provides\$1 - result 1 \(error\) is always nil
  - linters:
    - staticcheck
    # Code has a "Deprecated:" comment
    text: "SA1019:"
