//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchApproval) DeepCopyInto(out *DispatchApproval) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchApproval.
func (in *DispatchApproval) DeepCopy() *DispatchApproval {
	if in == nil {
		return nil
	}
	out := new(DispatchApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchAuditEvent) DeepCopyInto(out *DispatchAuditEvent) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchAuditEvent.
func (in *DispatchAuditEvent) DeepCopy() *DispatchAuditEvent {
	if in == nil {
		return nil
	}
	out := new(DispatchAuditEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchOverride) DeepCopyInto(out *DispatchOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchOverride.
func (in *DispatchOverride) DeepCopy() *DispatchOverride {
	if in == nil {
		return nil
	}
	out := new(DispatchOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DispatchOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchOverrideList) DeepCopyInto(out *DispatchOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DispatchOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchOverrideList.
func (in *DispatchOverrideList) DeepCopy() *DispatchOverrideList {
	if in == nil {
		return nil
	}
	out := new(DispatchOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DispatchOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchOverrideScope) DeepCopyInto(out *DispatchOverrideScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchOverrideScope.
func (in *DispatchOverrideScope) DeepCopy() *DispatchOverrideScope {
	if in == nil {
		return nil
	}
	out := new(DispatchOverrideScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchOverrideSpec) DeepCopyInto(out *DispatchOverrideSpec) {
	*out = *in
	out.Scope = in.Scope
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(int32)
		**out = **in
	}
	in.StartsAt.DeepCopyInto(&out.StartsAt)
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
	if in.Approvals != nil {
		in, out := &in.Approvals, &out.Approvals
		*out = make([]DispatchApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RevokedAt != nil {
		in, out := &in.RevokedAt, &out.RevokedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchOverrideSpec.
func (in *DispatchOverrideSpec) DeepCopy() *DispatchOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(DispatchOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchOverrideStatus) DeepCopyInto(out *DispatchOverrideStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]DispatchAuditEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchOverrideStatus.
func (in *DispatchOverrideStatus) DeepCopy() *DispatchOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(DispatchOverrideStatus)
	in.DeepCopyInto(out)
	return out
}
