//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	"k8s.io/test-infra/prow/apis/prowjobs/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildArg) DeepCopyInto(out *BuildArg) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildArg.
func (in *BuildArg) DeepCopy() *BuildArg {
	if in == nil {
		return nil
	}
	out := new(BuildArg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildRootImageConfiguration) DeepCopyInto(out *BuildRootImageConfiguration) {
	*out = *in
	if in.ImageStreamTagReference != nil {
		in, out := &in.ImageStreamTagReference, &out.ImageStreamTagReference
		*out = new(ImageStreamTagReference)
		**out = **in
	}
	if in.ProjectImageBuild != nil {
		in, out := &in.ProjectImageBuild, &out.ProjectImageBuild
		*out = new(ProjectDirectoryImageBuildInputs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildRootImageConfiguration.
func (in *BuildRootImageConfiguration) DeepCopy() *BuildRootImageConfiguration {
	if in == nil {
		return nil
	}
	out := new(BuildRootImageConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bundle) DeepCopyInto(out *Bundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bundle.
func (in *Bundle) DeepCopy() *Bundle {
	if in == nil {
		return nil
	}
	out := new(Bundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleSourceStepConfiguration) DeepCopyInto(out *BundleSourceStepConfiguration) {
	*out = *in
	if in.Substitutions != nil {
		in, out := &in.Substitutions, &out.Substitutions
		*out = make([]PullSpecSubstitution, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleSourceStepConfiguration.
func (in *BundleSourceStepConfiguration) DeepCopy() *BundleSourceStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(BundleSourceStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIOperatorInrepoConfig) DeepCopyInto(out *CIOperatorInrepoConfig) {
	*out = *in
	out.BuildRootImage = in.BuildRootImage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIOperatorInrepoConfig.
func (in *CIOperatorInrepoConfig) DeepCopy() *CIOperatorInrepoConfig {
	if in == nil {
		return nil
	}
	out := new(CIOperatorInrepoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Candidate) DeepCopyInto(out *Candidate) {
	*out = *in
	out.ReleaseDescriptor = in.ReleaseDescriptor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Candidate.
func (in *Candidate) DeepCopy() *Candidate {
	if in == nil {
		return nil
	}
	out := new(Candidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimRelease) DeepCopyInto(out *ClaimRelease) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimRelease.
func (in *ClaimRelease) DeepCopy() *ClaimRelease {
	if in == nil {
		return nil
	}
	out := new(ClaimRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterClaim) DeepCopyInto(out *ClusterClaim) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterClaim.
func (in *ClusterClaim) DeepCopy() *ClusterClaim {
	if in == nil {
		return nil
	}
	out := new(ClusterClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTestConfiguration) DeepCopyInto(out *ClusterTestConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTestConfiguration.
func (in *ClusterTestConfiguration) DeepCopy() *ClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(ClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerTestConfiguration) DeepCopyInto(out *ContainerTestConfiguration) {
	*out = *in
	if in.MemoryBackedVolume != nil {
		in, out := &in.MemoryBackedVolume, &out.MemoryBackedVolume
		*out = new(MemoryBackedVolume)
		**out = **in
	}
	if in.Clone != nil {
		in, out := &in.Clone, &out.Clone
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerTestConfiguration.
func (in *ContainerTestConfiguration) DeepCopy() *ContainerTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(ContainerTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialReference) DeepCopyInto(out *CredentialReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialReference.
func (in *CredentialReference) DeepCopy() *CredentialReference {
	if in == nil {
		return nil
	}
	out := new(CredentialReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in DependencyOverrides) DeepCopyInto(out *DependencyOverrides) {
	{
		in := &in
		*out = make(DependencyOverrides, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyOverrides.
func (in DependencyOverrides) DeepCopy() DependencyOverrides {
	if in == nil {
		return nil
	}
	out := new(DependencyOverrides)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphConfiguration) DeepCopyInto(out *GraphConfiguration) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]StepConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphConfiguration.
func (in *GraphConfiguration) DeepCopy() *GraphConfiguration {
	if in == nil {
		return nil
	}
	out := new(GraphConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageBuildInputs) DeepCopyInto(out *ImageBuildInputs) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]ImageSourcePath, len(*in))
		copy(*out, *in)
	}
	if in.As != nil {
		in, out := &in.As, &out.As
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageBuildInputs.
func (in *ImageBuildInputs) DeepCopy() *ImageBuildInputs {
	if in == nil {
		return nil
	}
	out := new(ImageBuildInputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSourcePath) DeepCopyInto(out *ImageSourcePath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSourcePath.
func (in *ImageSourcePath) DeepCopy() *ImageSourcePath {
	if in == nil {
		return nil
	}
	out := new(ImageSourcePath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageStreamSource) DeepCopyInto(out *ImageStreamSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageStreamSource.
func (in *ImageStreamSource) DeepCopy() *ImageStreamSource {
	if in == nil {
		return nil
	}
	out := new(ImageStreamSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageStreamTagReference) DeepCopyInto(out *ImageStreamTagReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageStreamTagReference.
func (in *ImageStreamTagReference) DeepCopy() *ImageStreamTagReference {
	if in == nil {
		return nil
	}
	out := new(ImageStreamTagReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexGeneratorStepConfiguration) DeepCopyInto(out *IndexGeneratorStepConfiguration) {
	*out = *in
	if in.OperatorIndex != nil {
		in, out := &in.OperatorIndex, &out.OperatorIndex
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexGeneratorStepConfiguration.
func (in *IndexGeneratorStepConfiguration) DeepCopy() *IndexGeneratorStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(IndexGeneratorStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputConfiguration) DeepCopyInto(out *InputConfiguration) {
	*out = *in
	if in.BaseImages != nil {
		in, out := &in.BaseImages, &out.BaseImages
		*out = make(map[string]ImageStreamTagReference, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BaseRPMImages != nil {
		in, out := &in.BaseRPMImages, &out.BaseRPMImages
		*out = make(map[string]ImageStreamTagReference, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BuildRootImage != nil {
		in, out := &in.BuildRootImage, &out.BuildRootImage
		*out = new(BuildRootImageConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ReleaseTagConfiguration != nil {
		in, out := &in.ReleaseTagConfiguration, &out.ReleaseTagConfiguration
		*out = new(ReleaseTagConfiguration)
		**out = **in
	}
	if in.Releases != nil {
		in, out := &in.Releases, &out.Releases
		*out = make(map[string]UnresolvedRelease, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputConfiguration.
func (in *InputConfiguration) DeepCopy() *InputConfiguration {
	if in == nil {
		return nil
	}
	out := new(InputConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in InputDefinition) DeepCopyInto(out *InputDefinition) {
	{
		in := &in
		*out = make(InputDefinition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputDefinition.
func (in InputDefinition) DeepCopy() InputDefinition {
	if in == nil {
		return nil
	}
	out := new(InputDefinition)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputImage) DeepCopyInto(out *InputImage) {
	*out = *in
	out.BaseImage = in.BaseImage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputImage.
func (in *InputImage) DeepCopy() *InputImage {
	if in == nil {
		return nil
	}
	out := new(InputImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputImageTagStepConfiguration) DeepCopyInto(out *InputImageTagStepConfiguration) {
	*out = *in
	out.InputImage = in.InputImage
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]ImageStreamSource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputImageTagStepConfiguration.
func (in *InputImageTagStepConfiguration) DeepCopy() *InputImageTagStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(InputImageTagStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Integration) DeepCopyInto(out *Integration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Integration.
func (in *Integration) DeepCopy() *Integration {
	if in == nil {
		return nil
	}
	out := new(Integration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiteralTestStep) DeepCopyInto(out *LiteralTestStep) {
	*out = *in
	if in.FromImage != nil {
		in, out := &in.FromImage, &out.FromImage
		*out = new(ImageStreamTagReference)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]CredentialReference, len(*in))
		copy(*out, *in)
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]StepParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]StepDependency, len(*in))
		copy(*out, *in)
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(StepDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Leases != nil {
		in, out := &in.Leases, &out.Leases
		*out = make([]StepLease, len(*in))
		copy(*out, *in)
	}
	if in.OptionalOnSuccess != nil {
		in, out := &in.OptionalOnSuccess, &out.OptionalOnSuccess
		*out = new(bool)
		**out = **in
	}
	if in.BestEffort != nil {
		in, out := &in.BestEffort, &out.BestEffort
		*out = new(bool)
		**out = **in
	}
	if in.NoKubeconfig != nil {
		in, out := &in.NoKubeconfig, &out.NoKubeconfig
		*out = new(bool)
		**out = **in
	}
	if in.Observers != nil {
		in, out := &in.Observers, &out.Observers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RunAsScript != nil {
		in, out := &in.RunAsScript, &out.RunAsScript
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiteralTestStep.
func (in *LiteralTestStep) DeepCopy() *LiteralTestStep {
	if in == nil {
		return nil
	}
	out := new(LiteralTestStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryBackedVolume) DeepCopyInto(out *MemoryBackedVolume) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryBackedVolume.
func (in *MemoryBackedVolume) DeepCopy() *MemoryBackedVolume {
	if in == nil {
		return nil
	}
	out := new(MemoryBackedVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metadata) DeepCopyInto(out *Metadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metadata.
func (in *Metadata) DeepCopy() *Metadata {
	if in == nil {
		return nil
	}
	out := new(Metadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataWithTest) DeepCopyInto(out *MetadataWithTest) {
	*out = *in
	out.Metadata = in.Metadata
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataWithTest.
func (in *MetadataWithTest) DeepCopy() *MetadataWithTest {
	if in == nil {
		return nil
	}
	out := new(MetadataWithTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiStageTestConfiguration) DeepCopyInto(out *MultiStageTestConfiguration) {
	*out = *in
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = make([]TestStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Test != nil {
		in, out := &in.Test, &out.Test
		*out = make([]TestStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]TestStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Workflow != nil {
		in, out := &in.Workflow, &out.Workflow
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make(TestEnvironment, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make(TestDependencies, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(StepDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Leases != nil {
		in, out := &in.Leases, &out.Leases
		*out = make([]StepLease, len(*in))
		copy(*out, *in)
	}
	if in.AllowSkipOnSuccess != nil {
		in, out := &in.AllowSkipOnSuccess, &out.AllowSkipOnSuccess
		*out = new(bool)
		**out = **in
	}
	if in.AllowBestEffortPostSteps != nil {
		in, out := &in.AllowBestEffortPostSteps, &out.AllowBestEffortPostSteps
		*out = new(bool)
		**out = **in
	}
	if in.Observers != nil {
		in, out := &in.Observers, &out.Observers
		*out = new(Observers)
		(*in).DeepCopyInto(*out)
	}
	if in.DependencyOverrides != nil {
		in, out := &in.DependencyOverrides, &out.DependencyOverrides
		*out = make(DependencyOverrides, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiStageTestConfiguration.
func (in *MultiStageTestConfiguration) DeepCopy() *MultiStageTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(MultiStageTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiStageTestConfigurationLiteral) DeepCopyInto(out *MultiStageTestConfigurationLiteral) {
	*out = *in
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = make([]LiteralTestStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Test != nil {
		in, out := &in.Test, &out.Test
		*out = make([]LiteralTestStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]LiteralTestStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make(TestEnvironment, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make(TestDependencies, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DNSConfig != nil {
		in, out := &in.DNSConfig, &out.DNSConfig
		*out = new(StepDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Leases != nil {
		in, out := &in.Leases, &out.Leases
		*out = make([]StepLease, len(*in))
		copy(*out, *in)
	}
	if in.AllowSkipOnSuccess != nil {
		in, out := &in.AllowSkipOnSuccess, &out.AllowSkipOnSuccess
		*out = new(bool)
		**out = **in
	}
	if in.AllowBestEffortPostSteps != nil {
		in, out := &in.AllowBestEffortPostSteps, &out.AllowBestEffortPostSteps
		*out = new(bool)
		**out = **in
	}
	if in.Observers != nil {
		in, out := &in.Observers, &out.Observers
		*out = make([]Observer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DependencyOverrides != nil {
		in, out := &in.DependencyOverrides, &out.DependencyOverrides
		*out = make(DependencyOverrides, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiStageTestConfigurationLiteral.
func (in *MultiStageTestConfigurationLiteral) DeepCopy() *MultiStageTestConfigurationLiteral {
	if in == nil {
		return nil
	}
	out := new(MultiStageTestConfigurationLiteral)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Observer) DeepCopyInto(out *Observer) {
	*out = *in
	if in.FromImage != nil {
		in, out := &in.FromImage, &out.FromImage
		*out = new(ImageStreamTagReference)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Observer.
func (in *Observer) DeepCopy() *Observer {
	if in == nil {
		return nil
	}
	out := new(Observer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Observers) DeepCopyInto(out *Observers) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Observers.
func (in *Observers) DeepCopy() *Observers {
	if in == nil {
		return nil
	}
	out := new(Observers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAnsible40ClusterTestConfiguration) DeepCopyInto(out *OpenshiftAnsible40ClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAnsible40ClusterTestConfiguration.
func (in *OpenshiftAnsible40ClusterTestConfiguration) DeepCopy() *OpenshiftAnsible40ClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAnsible40ClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAnsibleClusterTestConfiguration) DeepCopyInto(out *OpenshiftAnsibleClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAnsibleClusterTestConfiguration.
func (in *OpenshiftAnsibleClusterTestConfiguration) DeepCopy() *OpenshiftAnsibleClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAnsibleClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAnsibleCustomClusterTestConfiguration) DeepCopyInto(out *OpenshiftAnsibleCustomClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAnsibleCustomClusterTestConfiguration.
func (in *OpenshiftAnsibleCustomClusterTestConfiguration) DeepCopy() *OpenshiftAnsibleCustomClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAnsibleCustomClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAnsibleSrcClusterTestConfiguration) DeepCopyInto(out *OpenshiftAnsibleSrcClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAnsibleSrcClusterTestConfiguration.
func (in *OpenshiftAnsibleSrcClusterTestConfiguration) DeepCopy() *OpenshiftAnsibleSrcClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAnsibleSrcClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftInstallerClusterTestConfiguration) DeepCopyInto(out *OpenshiftInstallerClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftInstallerClusterTestConfiguration.
func (in *OpenshiftInstallerClusterTestConfiguration) DeepCopy() *OpenshiftInstallerClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftInstallerClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftInstallerConsoleClusterTestConfiguration) DeepCopyInto(out *OpenshiftInstallerConsoleClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftInstallerConsoleClusterTestConfiguration.
func (in *OpenshiftInstallerConsoleClusterTestConfiguration) DeepCopy() *OpenshiftInstallerConsoleClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftInstallerConsoleClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftInstallerCustomTestImageClusterTestConfiguration) DeepCopyInto(out *OpenshiftInstallerCustomTestImageClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftInstallerCustomTestImageClusterTestConfiguration.
func (in *OpenshiftInstallerCustomTestImageClusterTestConfiguration) DeepCopy() *OpenshiftInstallerCustomTestImageClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftInstallerCustomTestImageClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftInstallerGCPNestedVirtCustomTestImageClusterTestConfiguration) DeepCopyInto(out *OpenshiftInstallerGCPNestedVirtCustomTestImageClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftInstallerGCPNestedVirtCustomTestImageClusterTestConfiguration.
func (in *OpenshiftInstallerGCPNestedVirtCustomTestImageClusterTestConfiguration) DeepCopy() *OpenshiftInstallerGCPNestedVirtCustomTestImageClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftInstallerGCPNestedVirtCustomTestImageClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftInstallerRandomClusterTestConfiguration) DeepCopyInto(out *OpenshiftInstallerRandomClusterTestConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftInstallerRandomClusterTestConfiguration.
func (in *OpenshiftInstallerRandomClusterTestConfiguration) DeepCopy() *OpenshiftInstallerRandomClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftInstallerRandomClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftInstallerSrcClusterTestConfiguration) DeepCopyInto(out *OpenshiftInstallerSrcClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftInstallerSrcClusterTestConfiguration.
func (in *OpenshiftInstallerSrcClusterTestConfiguration) DeepCopy() *OpenshiftInstallerSrcClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftInstallerSrcClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftInstallerUPIClusterTestConfiguration) DeepCopyInto(out *OpenshiftInstallerUPIClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftInstallerUPIClusterTestConfiguration.
func (in *OpenshiftInstallerUPIClusterTestConfiguration) DeepCopy() *OpenshiftInstallerUPIClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftInstallerUPIClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftInstallerUPISrcClusterTestConfiguration) DeepCopyInto(out *OpenshiftInstallerUPISrcClusterTestConfiguration) {
	*out = *in
	out.ClusterTestConfiguration = in.ClusterTestConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftInstallerUPISrcClusterTestConfiguration.
func (in *OpenshiftInstallerUPISrcClusterTestConfiguration) DeepCopy() *OpenshiftInstallerUPISrcClusterTestConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenshiftInstallerUPISrcClusterTestConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorStepConfiguration) DeepCopyInto(out *OperatorStepConfiguration) {
	*out = *in
	if in.Bundles != nil {
		in, out := &in.Bundles, &out.Bundles
		*out = make([]Bundle, len(*in))
		copy(*out, *in)
	}
	if in.Substitutions != nil {
		in, out := &in.Substitutions, &out.Substitutions
		*out = make([]PullSpecSubstitution, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorStepConfiguration.
func (in *OperatorStepConfiguration) DeepCopy() *OperatorStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(OperatorStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputImageTagStepConfiguration) DeepCopyInto(out *OutputImageTagStepConfiguration) {
	*out = *in
	out.To = in.To
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputImageTagStepConfiguration.
func (in *OutputImageTagStepConfiguration) DeepCopy() *OutputImageTagStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(OutputImageTagStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineImageCacheStepConfiguration) DeepCopyInto(out *PipelineImageCacheStepConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineImageCacheStepConfiguration.
func (in *PipelineImageCacheStepConfiguration) DeepCopy() *PipelineImageCacheStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(PipelineImageCacheStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prerelease) DeepCopyInto(out *Prerelease) {
	*out = *in
	out.ReleaseDescriptor = in.ReleaseDescriptor
	out.VersionBounds = in.VersionBounds
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prerelease.
func (in *Prerelease) DeepCopy() *Prerelease {
	if in == nil {
		return nil
	}
	out := new(Prerelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDirectoryImageBuildInputs) DeepCopyInto(out *ProjectDirectoryImageBuildInputs) {
	*out = *in
	if in.DockerfileLiteral != nil {
		in, out := &in.DockerfileLiteral, &out.DockerfileLiteral
		*out = new(string)
		**out = **in
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(map[string]ImageBuildInputs, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.BuildArgs != nil {
		in, out := &in.BuildArgs, &out.BuildArgs
		*out = make([]BuildArg, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDirectoryImageBuildInputs.
func (in *ProjectDirectoryImageBuildInputs) DeepCopy() *ProjectDirectoryImageBuildInputs {
	if in == nil {
		return nil
	}
	out := new(ProjectDirectoryImageBuildInputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDirectoryImageBuildStepConfiguration) DeepCopyInto(out *ProjectDirectoryImageBuildStepConfiguration) {
	*out = *in
	in.ProjectDirectoryImageBuildInputs.DeepCopyInto(&out.ProjectDirectoryImageBuildInputs)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDirectoryImageBuildStepConfiguration.
func (in *ProjectDirectoryImageBuildStepConfiguration) DeepCopy() *ProjectDirectoryImageBuildStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProjectDirectoryImageBuildStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionConfiguration) DeepCopyInto(out *PromotionConfiguration) {
	*out = *in
	if in.ExcludedImages != nil {
		in, out := &in.ExcludedImages, &out.ExcludedImages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalImages != nil {
		in, out := &in.AdditionalImages, &out.AdditionalImages
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionConfiguration.
func (in *PromotionConfiguration) DeepCopy() *PromotionConfiguration {
	if in == nil {
		return nil
	}
	out := new(PromotionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullSpecSubstitution) DeepCopyInto(out *PullSpecSubstitution) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullSpecSubstitution.
func (in *PullSpecSubstitution) DeepCopy() *PullSpecSubstitution {
	if in == nil {
		return nil
	}
	out := new(PullSpecSubstitution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPMImageInjectionStepConfiguration) DeepCopyInto(out *RPMImageInjectionStepConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPMImageInjectionStepConfiguration.
func (in *RPMImageInjectionStepConfiguration) DeepCopy() *RPMImageInjectionStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(RPMImageInjectionStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPMServeStepConfiguration) DeepCopyInto(out *RPMServeStepConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPMServeStepConfiguration.
func (in *RPMServeStepConfiguration) DeepCopy() *RPMServeStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(RPMServeStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryChain) DeepCopyInto(out *RegistryChain) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]TestStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]StepParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Leases != nil {
		in, out := &in.Leases, &out.Leases
		*out = make([]StepLease, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryChain.
func (in *RegistryChain) DeepCopy() *RegistryChain {
	if in == nil {
		return nil
	}
	out := new(RegistryChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryChainConfig) DeepCopyInto(out *RegistryChainConfig) {
	*out = *in
	in.Chain.DeepCopyInto(&out.Chain)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryChainConfig.
func (in *RegistryChainConfig) DeepCopy() *RegistryChainConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryChainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryObserver) DeepCopyInto(out *RegistryObserver) {
	*out = *in
	in.Observer.DeepCopyInto(&out.Observer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryObserver.
func (in *RegistryObserver) DeepCopy() *RegistryObserver {
	if in == nil {
		return nil
	}
	out := new(RegistryObserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryObserverConfig) DeepCopyInto(out *RegistryObserverConfig) {
	*out = *in
	in.Observer.DeepCopyInto(&out.Observer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryObserverConfig.
func (in *RegistryObserverConfig) DeepCopy() *RegistryObserverConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryObserverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryReference) DeepCopyInto(out *RegistryReference) {
	*out = *in
	in.LiteralTestStep.DeepCopyInto(&out.LiteralTestStep)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryReference.
func (in *RegistryReference) DeepCopy() *RegistryReference {
	if in == nil {
		return nil
	}
	out := new(RegistryReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryReferenceConfig) DeepCopyInto(out *RegistryReferenceConfig) {
	*out = *in
	in.Reference.DeepCopyInto(&out.Reference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryReferenceConfig.
func (in *RegistryReferenceConfig) DeepCopy() *RegistryReferenceConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryReferenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryWorkflow) DeepCopyInto(out *RegistryWorkflow) {
	*out = *in
	in.Steps.DeepCopyInto(&out.Steps)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryWorkflow.
func (in *RegistryWorkflow) DeepCopy() *RegistryWorkflow {
	if in == nil {
		return nil
	}
	out := new(RegistryWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryWorkflowConfig) DeepCopyInto(out *RegistryWorkflowConfig) {
	*out = *in
	in.Workflow.DeepCopyInto(&out.Workflow)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryWorkflowConfig.
func (in *RegistryWorkflowConfig) DeepCopy() *RegistryWorkflowConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryWorkflowConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Release) DeepCopyInto(out *Release) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Release.
func (in *Release) DeepCopy() *Release {
	if in == nil {
		return nil
	}
	out := new(Release)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseBuildConfiguration) DeepCopyInto(out *ReleaseBuildConfiguration) {
	*out = *in
	out.Metadata = in.Metadata
	in.InputConfiguration.DeepCopyInto(&out.InputConfiguration)
	if in.CanonicalGoRepository != nil {
		in, out := &in.CanonicalGoRepository, &out.CanonicalGoRepository
		*out = new(string)
		**out = **in
	}
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]ProjectDirectoryImageBuildStepConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(OperatorStepConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = make([]TestStepConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RawSteps != nil {
		in, out := &in.RawSteps, &out.RawSteps
		*out = make([]StepConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PromotionConfiguration != nil {
		in, out := &in.PromotionConfiguration, &out.PromotionConfiguration
		*out = new(PromotionConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(ResourceConfiguration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseBuildConfiguration.
func (in *ReleaseBuildConfiguration) DeepCopy() *ReleaseBuildConfiguration {
	if in == nil {
		return nil
	}
	out := new(ReleaseBuildConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseConfiguration) DeepCopyInto(out *ReleaseConfiguration) {
	*out = *in
	in.UnresolvedRelease.DeepCopyInto(&out.UnresolvedRelease)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseConfiguration.
func (in *ReleaseConfiguration) DeepCopy() *ReleaseConfiguration {
	if in == nil {
		return nil
	}
	out := new(ReleaseConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseDescriptor) DeepCopyInto(out *ReleaseDescriptor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseDescriptor.
func (in *ReleaseDescriptor) DeepCopy() *ReleaseDescriptor {
	if in == nil {
		return nil
	}
	out := new(ReleaseDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseTagConfiguration) DeepCopyInto(out *ReleaseTagConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseTagConfiguration.
func (in *ReleaseTagConfiguration) DeepCopy() *ReleaseTagConfiguration {
	if in == nil {
		return nil
	}
	out := new(ReleaseTagConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ResourceConfiguration) DeepCopyInto(out *ResourceConfiguration) {
	{
		in := &in
		*out = make(ResourceConfiguration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfiguration.
func (in ResourceConfiguration) DeepCopy() ResourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ResourceConfiguration)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ResourceList) DeepCopyInto(out *ResourceList) {
	{
		in := &in
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceList.
func (in ResourceList) DeepCopy() ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceStepConfiguration) DeepCopyInto(out *SourceStepConfiguration) {
	*out = *in
	out.ClonerefsImage = in.ClonerefsImage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceStepConfiguration.
func (in *SourceStepConfiguration) DeepCopy() *SourceStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(SourceStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepConfiguration) DeepCopyInto(out *StepConfiguration) {
	*out = *in
	if in.InputImageTagStepConfiguration != nil {
		in, out := &in.InputImageTagStepConfiguration, &out.InputImageTagStepConfiguration
		*out = new(InputImageTagStepConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.PipelineImageCacheStepConfiguration != nil {
		in, out := &in.PipelineImageCacheStepConfiguration, &out.PipelineImageCacheStepConfiguration
		*out = new(PipelineImageCacheStepConfiguration)
		**out = **in
	}
	if in.SourceStepConfiguration != nil {
		in, out := &in.SourceStepConfiguration, &out.SourceStepConfiguration
		*out = new(SourceStepConfiguration)
		**out = **in
	}
	if in.BundleSourceStepConfiguration != nil {
		in, out := &in.BundleSourceStepConfiguration, &out.BundleSourceStepConfiguration
		*out = new(BundleSourceStepConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.IndexGeneratorStepConfiguration != nil {
		in, out := &in.IndexGeneratorStepConfiguration, &out.IndexGeneratorStepConfiguration
		*out = new(IndexGeneratorStepConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectDirectoryImageBuildStepConfiguration != nil {
		in, out := &in.ProjectDirectoryImageBuildStepConfiguration, &out.ProjectDirectoryImageBuildStepConfiguration
		*out = new(ProjectDirectoryImageBuildStepConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RPMImageInjectionStepConfiguration != nil {
		in, out := &in.RPMImageInjectionStepConfiguration, &out.RPMImageInjectionStepConfiguration
		*out = new(RPMImageInjectionStepConfiguration)
		**out = **in
	}
	if in.RPMServeStepConfiguration != nil {
		in, out := &in.RPMServeStepConfiguration, &out.RPMServeStepConfiguration
		*out = new(RPMServeStepConfiguration)
		**out = **in
	}
	if in.OutputImageTagStepConfiguration != nil {
		in, out := &in.OutputImageTagStepConfiguration, &out.OutputImageTagStepConfiguration
		*out = new(OutputImageTagStepConfiguration)
		**out = **in
	}
	if in.ReleaseImagesTagStepConfiguration != nil {
		in, out := &in.ReleaseImagesTagStepConfiguration, &out.ReleaseImagesTagStepConfiguration
		*out = new(ReleaseTagConfiguration)
		**out = **in
	}
	if in.ResolvedReleaseImagesStepConfiguration != nil {
		in, out := &in.ResolvedReleaseImagesStepConfiguration, &out.ResolvedReleaseImagesStepConfiguration
		*out = new(ReleaseConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.TestStepConfiguration != nil {
		in, out := &in.TestStepConfiguration, &out.TestStepConfiguration
		*out = new(TestStepConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ProjectDirectoryImageBuildInputs != nil {
		in, out := &in.ProjectDirectoryImageBuildInputs, &out.ProjectDirectoryImageBuildInputs
		*out = new(ProjectDirectoryImageBuildInputs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepConfiguration.
func (in *StepConfiguration) DeepCopy() *StepConfiguration {
	if in == nil {
		return nil
	}
	out := new(StepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepDNSConfig) DeepCopyInto(out *StepDNSConfig) {
	*out = *in
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Searches != nil {
		in, out := &in.Searches, &out.Searches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepDNSConfig.
func (in *StepDNSConfig) DeepCopy() *StepDNSConfig {
	if in == nil {
		return nil
	}
	out := new(StepDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepDependency) DeepCopyInto(out *StepDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepDependency.
func (in *StepDependency) DeepCopy() *StepDependency {
	if in == nil {
		return nil
	}
	out := new(StepDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepLease) DeepCopyInto(out *StepLease) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepLease.
func (in *StepLease) DeepCopy() *StepLease {
	if in == nil {
		return nil
	}
	out := new(StepLease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepLinkOptions) DeepCopyInto(out *StepLinkOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepLinkOptions.
func (in *StepLinkOptions) DeepCopy() *StepLinkOptions {
	if in == nil {
		return nil
	}
	out := new(StepLinkOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepParameter) DeepCopyInto(out *StepParameter) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepParameter.
func (in *StepParameter) DeepCopy() *StepParameter {
	if in == nil {
		return nil
	}
	out := new(StepParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TestDependencies) DeepCopyInto(out *TestDependencies) {
	{
		in := &in
		*out = make(TestDependencies, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestDependencies.
func (in TestDependencies) DeepCopy() TestDependencies {
	if in == nil {
		return nil
	}
	out := new(TestDependencies)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in TestEnvironment) DeepCopyInto(out *TestEnvironment) {
	{
		in := &in
		*out = make(TestEnvironment, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestEnvironment.
func (in TestEnvironment) DeepCopy() TestEnvironment {
	if in == nil {
		return nil
	}
	out := new(TestEnvironment)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestStep) DeepCopyInto(out *TestStep) {
	*out = *in
	if in.LiteralTestStep != nil {
		in, out := &in.LiteralTestStep, &out.LiteralTestStep
		*out = new(LiteralTestStep)
		(*in).DeepCopyInto(*out)
	}
	if in.Reference != nil {
		in, out := &in.Reference, &out.Reference
		*out = new(string)
		**out = **in
	}
	if in.Chain != nil {
		in, out := &in.Chain, &out.Chain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestStep.
func (in *TestStep) DeepCopy() *TestStep {
	if in == nil {
		return nil
	}
	out := new(TestStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestStepConfiguration) DeepCopyInto(out *TestStepConfiguration) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(Secret)
		**out = **in
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]*Secret, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Secret)
				**out = **in
			}
		}
	}
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.MinimumInterval != nil {
		in, out := &in.MinimumInterval, &out.MinimumInterval
		*out = new(string)
		**out = **in
	}
	if in.ClusterClaim != nil {
		in, out := &in.ClusterClaim, &out.ClusterClaim
		*out = new(ClusterClaim)
		(*in).DeepCopyInto(*out)
	}
	if in.AlwaysRun != nil {
		in, out := &in.AlwaysRun, &out.AlwaysRun
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ContainerTestConfiguration != nil {
		in, out := &in.ContainerTestConfiguration, &out.ContainerTestConfiguration
		*out = new(ContainerTestConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiStageTestConfiguration != nil {
		in, out := &in.MultiStageTestConfiguration, &out.MultiStageTestConfiguration
		*out = new(MultiStageTestConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiStageTestConfigurationLiteral != nil {
		in, out := &in.MultiStageTestConfigurationLiteral, &out.MultiStageTestConfigurationLiteral
		*out = new(MultiStageTestConfigurationLiteral)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenshiftAnsibleClusterTestConfiguration != nil {
		in, out := &in.OpenshiftAnsibleClusterTestConfiguration, &out.OpenshiftAnsibleClusterTestConfiguration
		*out = new(OpenshiftAnsibleClusterTestConfiguration)
		**out = **in
	}
	if in.OpenshiftAnsibleSrcClusterTestConfiguration != nil {
		in, out := &in.OpenshiftAnsibleSrcClusterTestConfiguration, &out.OpenshiftAnsibleSrcClusterTestConfiguration
		*out = new(OpenshiftAnsibleSrcClusterTestConfiguration)
		**out = **in
	}
	if in.OpenshiftAnsibleCustomClusterTestConfiguration != nil {
		in, out := &in.OpenshiftAnsibleCustomClusterTestConfiguration, &out.OpenshiftAnsibleCustomClusterTestConfiguration
		*out = new(OpenshiftAnsibleCustomClusterTestConfiguration)
		**out = **in
	}
	if in.OpenshiftInstallerClusterTestConfiguration != nil {
		in, out := &in.OpenshiftInstallerClusterTestConfiguration, &out.OpenshiftInstallerClusterTestConfiguration
		*out = new(OpenshiftInstallerClusterTestConfiguration)
		**out = **in
	}
	if in.OpenshiftInstallerUPIClusterTestConfiguration != nil {
		in, out := &in.OpenshiftInstallerUPIClusterTestConfiguration, &out.OpenshiftInstallerUPIClusterTestConfiguration
		*out = new(OpenshiftInstallerUPIClusterTestConfiguration)
		**out = **in
	}
	if in.OpenshiftInstallerUPISrcClusterTestConfiguration != nil {
		in, out := &in.OpenshiftInstallerUPISrcClusterTestConfiguration, &out.OpenshiftInstallerUPISrcClusterTestConfiguration
		*out = new(OpenshiftInstallerUPISrcClusterTestConfiguration)
		**out = **in
	}
	if in.OpenshiftInstallerCustomTestImageClusterTestConfiguration != nil {
		in, out := &in.OpenshiftInstallerCustomTestImageClusterTestConfiguration, &out.OpenshiftInstallerCustomTestImageClusterTestConfiguration
		*out = new(OpenshiftInstallerCustomTestImageClusterTestConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestStepConfiguration.
func (in *TestStepConfiguration) DeepCopy() *TestStepConfiguration {
	if in == nil {
		return nil
	}
	out := new(TestStepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnresolvedRelease) DeepCopyInto(out *UnresolvedRelease) {
	*out = *in
	if in.Integration != nil {
		in, out := &in.Integration, &out.Integration
		*out = new(Integration)
		**out = **in
	}
	if in.Candidate != nil {
		in, out := &in.Candidate, &out.Candidate
		*out = new(Candidate)
		**out = **in
	}
	if in.Prerelease != nil {
		in, out := &in.Prerelease, &out.Prerelease
		*out = new(Prerelease)
		**out = **in
	}
	if in.Release != nil {
		in, out := &in.Release, &out.Release
		*out = new(Release)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnresolvedRelease.
func (in *UnresolvedRelease) DeepCopy() *UnresolvedRelease {
	if in == nil {
		return nil
	}
	out := new(UnresolvedRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionBounds) DeepCopyInto(out *VersionBounds) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionBounds.
func (in *VersionBounds) DeepCopy() *VersionBounds {
	if in == nil {
		return nil
	}
	out := new(VersionBounds)
	in.DeepCopyInto(out)
	return out
}
