package prowgen

import (
	"fmt"
	"regexp"
	"strconv"

	"github.com/ghodss/yaml"

	"github.com/openshift/ci-tools/pkg/api"
	"github.com/openshift/ci-tools/pkg/util/gzip"
)

// ManagedRepo configures which branches of an org/repo are "managed"
// elsewhere (e.g. onboarded onto EFS, generated by a different tool) and
// therefore should not be touched by the normal ci-operator-prowgen path.
//
// A branch is managed if it matches Branches, or AllBranches is set, or it
// is a release-X.Y branch at or after FromRelease — unless it is also
// listed in ExcludeBranches, which always wins.
type ManagedRepo struct {
	// AllBranches, if true, means every branch of this repo is managed,
	// except any listed in ExcludeBranches.
	AllBranches bool `json:"allBranches,omitempty"`
	// FromRelease, if set to a MAJOR.MINOR version (e.g. "4.22"), means
	// release-X.Y branches at or after this version are managed. Older
	// release-X.Y branches and non-release branches (e.g. main) are not
	// managed by this rule alone. Can be combined with AllBranches (which
	// makes FromRelease redundant) or used on its own for a mixed-mode
	// repo that is only partially managed.
	FromRelease string `json:"fromRelease,omitempty"`
	// Branches lists additional specific branches that are managed,
	// regardless of AllBranches/FromRelease. Useful for branches that
	// don't follow the release-X.Y naming convention.
	Branches []string `json:"branches,omitempty"`
	// ExcludeBranches lists branches that are never managed, overriding
	// AllBranches, FromRelease and Branches for those specific names. This
	// is an escape hatch, e.g. to keep one specific branch on the normal
	// generation path while the rest of the repo has moved.
	ExcludeBranches []string `json:"excludeBranches,omitempty"`
}

func (r *ManagedRepo) isManaged(branch string) bool {
	if r == nil {
		return false
	}
	for _, b := range r.ExcludeBranches {
		if b == branch {
			return false
		}
	}
	for _, b := range r.Branches {
		if b == branch {
			return true
		}
	}
	if r.AllBranches {
		return true
	}
	if r.FromRelease != "" {
		// Errors are ignored here: LoadManagedReposConfig validates
		// FromRelease up front, so this only stays silent for configs
		// constructed directly (e.g. in tests) with an invalid value.
		if min, err := api.ParseVersion(r.FromRelease); err == nil {
			if v, ok := releaseVersionFromBranch(branch); ok {
				return versionAtLeast(v, min)
			}
		}
	}
	return false
}

// ManagedReposConfig configures, by org/repo, which branches are managed
// elsewhere and should be left alone by the normal ci-operator-prowgen path
// (or, conversely, be the *only* branches processed by a tool generating
// jobs for the other, managed side, e.g. a postsubmit writing to EFS).
type ManagedReposConfig struct {
	// Repos maps "org/repo" to its managed-branches configuration.
	Repos map[string]ManagedRepo `json:"repos,omitempty"`
}

// IsManaged reports whether orgRepo (formatted as "org/repo") @ branch is
// managed per the configuration. A nil *ManagedReposConfig manages nothing.
func (c *ManagedReposConfig) IsManaged(orgRepo, branch string) bool {
	if c == nil {
		return false
	}
	repo, ok := c.Repos[orgRepo]
	if !ok {
		return false
	}
	return repo.isManaged(branch)
}

// LoadManagedReposConfig reads and validates a ManagedReposConfig from a
// YAML file. An empty path returns a nil config (nothing managed).
func LoadManagedReposConfig(path string) (*ManagedReposConfig, error) {
	if path == "" {
		return nil, nil
	}
	data, err := gzip.ReadFileMaybeGZIP(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", path, err)
	}
	var cfg ManagedReposConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("failed to unmarshal %s: %w", path, err)
	}
	for orgRepo, repo := range cfg.Repos {
		if repo.FromRelease != "" {
			if _, err := api.ParseVersion(repo.FromRelease); err != nil {
				return nil, fmt.Errorf("%s: repo %q: invalid fromRelease: %w", path, orgRepo, err)
			}
		}
	}
	return &cfg, nil
}

// versionAtLeast reports whether v >= other.
func versionAtLeast(v, other api.ParsedVersion) bool {
	if v.Major != other.Major {
		return v.Major > other.Major
	}
	return v.Minor >= other.Minor
}

var releaseBranchRE = regexp.MustCompile(`^release-(\d+)\.(\d+)$`)

// releaseVersionFromBranch extracts the OCP release version encoded in
// branch names like "release-4.22". Branches that don't follow this
// convention (main, master, feature branches, ...) return ok=false.
func releaseVersionFromBranch(branch string) (api.ParsedVersion, bool) {
	m := releaseBranchRE.FindStringSubmatch(branch)
	if m == nil {
		return api.ParsedVersion{}, false
	}
	major, err := strconv.Atoi(m[1])
	if err != nil {
		return api.ParsedVersion{}, false
	}
	minor, err := strconv.Atoi(m[2])
	if err != nil {
		return api.ParsedVersion{}, false
	}
	return api.ParsedVersion{Major: major, Minor: minor}, true
}
