//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/openshift/ci-tools/pkg/api"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIOperatorSpec) DeepCopyInto(out *CIOperatorSpec) {
	*out = *in
	if in.BuildRootImage != nil {
		in, out := &in.BuildRootImage, &out.BuildRootImage
		*out = new(api.BuildRootImageConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.BaseImages != nil {
		in, out := &in.BaseImages, &out.BaseImages
		*out = make(map[string]api.ImageStreamTagReference, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExternalImages != nil {
		in, out := &in.ExternalImages, &out.ExternalImages
		*out = make(map[string]api.ExternalImage, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Releases != nil {
		in, out := &in.Releases, &out.Releases
		*out = make(map[string]api.UnresolvedRelease, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(api.ResourceConfiguration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.Test.DeepCopyInto(&out.Test)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIOperatorSpec.
func (in *CIOperatorSpec) DeepCopy() *CIOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(CIOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralCluster) DeepCopyInto(out *EphemeralCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralCluster.
func (in *EphemeralCluster) DeepCopy() *EphemeralCluster {
	if in == nil {
		return nil
	}
	out := new(EphemeralCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EphemeralCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralClusterCondition) DeepCopyInto(out *EphemeralClusterCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralClusterCondition.
func (in *EphemeralClusterCondition) DeepCopy() *EphemeralClusterCondition {
	if in == nil {
		return nil
	}
	out := new(EphemeralClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralClusterList) DeepCopyInto(out *EphemeralClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EphemeralCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralClusterList.
func (in *EphemeralClusterList) DeepCopy() *EphemeralClusterList {
	if in == nil {
		return nil
	}
	out := new(EphemeralClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EphemeralClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralClusterSpec) DeepCopyInto(out *EphemeralClusterSpec) {
	*out = *in
	in.CIOperator.DeepCopyInto(&out.CIOperator)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralClusterSpec.
func (in *EphemeralClusterSpec) DeepCopy() *EphemeralClusterSpec {
	if in == nil {
		return nil
	}
	out := new(EphemeralClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralClusterStatus) DeepCopyInto(out *EphemeralClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]EphemeralClusterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralClusterStatus.
func (in *EphemeralClusterStatus) DeepCopy() *EphemeralClusterStatus {
	if in == nil {
		return nil
	}
	out := new(EphemeralClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestMeta) DeepCopyInto(out *PullRequestMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestMeta.
func (in *PullRequestMeta) DeepCopy() *PullRequestMeta {
	if in == nil {
		return nil
	}
	out := new(PullRequestMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpec) DeepCopyInto(out *TestSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClusterClaim != nil {
		in, out := &in.ClusterClaim, &out.ClusterClaim
		*out = new(api.ClusterClaim)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpec.
func (in *TestSpec) DeepCopy() *TestSpec {
	if in == nil {
		return nil
	}
	out := new(TestSpec)
	in.DeepCopyInto(out)
	return out
}
