// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/ci-tools/pkg/jobrunaggregator/jobrunaggregatorapi (interfaces: JobRunInfo)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -destination=pkg/jobrunaggregator/jobrunaggregatorapi/jobruninfo_mock.go -package=jobrunaggregatorapi github.com/openshift/ci-tools/pkg/jobrunaggregator/jobrunaggregatorapi JobRunInfo
//

// Package jobrunaggregatorapi is a generated GoMock package.
package jobrunaggregatorapi

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	v1 "sigs.k8s.io/prow/pkg/apis/prowjobs/v1"

	junit "github.com/openshift/ci-tools/pkg/junit"
)

// MockJobRunInfo is a mock of JobRunInfo interface.
type MockJobRunInfo struct {
	ctrl     *gomock.Controller
	recorder *MockJobRunInfoMockRecorder
	isgomock struct{}
}

// MockJobRunInfoMockRecorder is the mock recorder for MockJobRunInfo.
type MockJobRunInfoMockRecorder struct {
	mock *MockJobRunInfo
}

// NewMockJobRunInfo creates a new mock instance.
func NewMockJobRunInfo(ctrl *gomock.Controller) *MockJobRunInfo {
	mock := &MockJobRunInfo{ctrl: ctrl}
	mock.recorder = &MockJobRunInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRunInfo) EXPECT() *MockJobRunInfoMockRecorder {
	return m.recorder
}

// AddGCSJunitPaths mocks base method.
func (m *MockJobRunInfo) AddGCSJunitPaths(junitPaths ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range junitPaths {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddGCSJunitPaths", varargs...)
}

// AddGCSJunitPaths indicates an expected call of AddGCSJunitPaths.
func (mr *MockJobRunInfoMockRecorder) AddGCSJunitPaths(junitPaths ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGCSJunitPaths", reflect.TypeOf((*MockJobRunInfo)(nil).AddGCSJunitPaths), junitPaths...)
}

// AddGCSProwJobFileNames mocks base method.
func (m *MockJobRunInfo) AddGCSProwJobFileNames(fileNames ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range fileNames {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddGCSProwJobFileNames", varargs...)
}

// AddGCSProwJobFileNames indicates an expected call of AddGCSProwJobFileNames.
func (mr *MockJobRunInfoMockRecorder) AddGCSProwJobFileNames(fileNames ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGCSProwJobFileNames", reflect.TypeOf((*MockJobRunInfo)(nil).AddGCSProwJobFileNames), fileNames...)
}

// ClearAllContent mocks base method.
func (m *MockJobRunInfo) ClearAllContent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearAllContent")
}

// ClearAllContent indicates an expected call of ClearAllContent.
func (mr *MockJobRunInfoMockRecorder) ClearAllContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAllContent", reflect.TypeOf((*MockJobRunInfo)(nil).ClearAllContent))
}

// GetCombinedJUnitTestSuites mocks base method.
func (m *MockJobRunInfo) GetCombinedJUnitTestSuites(ctx context.Context) (*junit.TestSuites, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCombinedJUnitTestSuites", ctx)
	ret0, _ := ret[0].(*junit.TestSuites)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCombinedJUnitTestSuites indicates an expected call of GetCombinedJUnitTestSuites.
func (mr *MockJobRunInfoMockRecorder) GetCombinedJUnitTestSuites(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCombinedJUnitTestSuites", reflect.TypeOf((*MockJobRunInfo)(nil).GetCombinedJUnitTestSuites), ctx)
}

// GetContent mocks base method.
func (m *MockJobRunInfo) GetContent(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockJobRunInfoMockRecorder) GetContent(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockJobRunInfo)(nil).GetContent), ctx, path)
}

// GetGCSArtifactURL mocks base method.
func (m *MockJobRunInfo) GetGCSArtifactURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGCSArtifactURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGCSArtifactURL indicates an expected call of GetGCSArtifactURL.
func (mr *MockJobRunInfoMockRecorder) GetGCSArtifactURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGCSArtifactURL", reflect.TypeOf((*MockJobRunInfo)(nil).GetGCSArtifactURL))
}

// GetGCSJunitPaths mocks base method.
func (m *MockJobRunInfo) GetGCSJunitPaths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGCSJunitPaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetGCSJunitPaths indicates an expected call of GetGCSJunitPaths.
func (mr *MockJobRunInfoMockRecorder) GetGCSJunitPaths() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGCSJunitPaths", reflect.TypeOf((*MockJobRunInfo)(nil).GetGCSJunitPaths))
}

// GetGCSProwJobPath mocks base method.
func (m *MockJobRunInfo) GetGCSProwJobPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGCSProwJobPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGCSProwJobPath indicates an expected call of GetGCSProwJobPath.
func (mr *MockJobRunInfoMockRecorder) GetGCSProwJobPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGCSProwJobPath", reflect.TypeOf((*MockJobRunInfo)(nil).GetGCSProwJobPath))
}

// GetHumanURL mocks base method.
func (m *MockJobRunInfo) GetHumanURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHumanURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHumanURL indicates an expected call of GetHumanURL.
func (mr *MockJobRunInfoMockRecorder) GetHumanURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHumanURL", reflect.TypeOf((*MockJobRunInfo)(nil).GetHumanURL))
}

// GetJobName mocks base method.
func (m *MockJobRunInfo) GetJobName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJobName indicates an expected call of GetJobName.
func (mr *MockJobRunInfoMockRecorder) GetJobName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobName", reflect.TypeOf((*MockJobRunInfo)(nil).GetJobName))
}

// GetJobRunFromGCS mocks base method.
func (m *MockJobRunInfo) GetJobRunFromGCS(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobRunFromGCS", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetJobRunFromGCS indicates an expected call of GetJobRunFromGCS.
func (mr *MockJobRunInfoMockRecorder) GetJobRunFromGCS(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobRunFromGCS", reflect.TypeOf((*MockJobRunInfo)(nil).GetJobRunFromGCS), ctx)
}

// GetJobRunID mocks base method.
func (m *MockJobRunInfo) GetJobRunID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobRunID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetJobRunID indicates an expected call of GetJobRunID.
func (mr *MockJobRunInfoMockRecorder) GetJobRunID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobRunID", reflect.TypeOf((*MockJobRunInfo)(nil).GetJobRunID))
}

// GetOpenShiftTestsFilesWithPrefix mocks base method.
func (m *MockJobRunInfo) GetOpenShiftTestsFilesWithPrefix(ctx context.Context, prefix string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenShiftTestsFilesWithPrefix", ctx, prefix)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenShiftTestsFilesWithPrefix indicates an expected call of GetOpenShiftTestsFilesWithPrefix.
func (mr *MockJobRunInfoMockRecorder) GetOpenShiftTestsFilesWithPrefix(ctx, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenShiftTestsFilesWithPrefix", reflect.TypeOf((*MockJobRunInfo)(nil).GetOpenShiftTestsFilesWithPrefix), ctx, prefix)
}

// GetProwJob mocks base method.
func (m *MockJobRunInfo) GetProwJob(ctx context.Context) (*v1.ProwJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProwJob", ctx)
	ret0, _ := ret[0].(*v1.ProwJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProwJob indicates an expected call of GetProwJob.
func (mr *MockJobRunInfoMockRecorder) GetProwJob(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProwJob", reflect.TypeOf((*MockJobRunInfo)(nil).GetProwJob), ctx)
}

// IsFinished mocks base method.
func (m *MockJobRunInfo) IsFinished(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFinished", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFinished indicates an expected call of IsFinished.
func (mr *MockJobRunInfoMockRecorder) IsFinished(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFinished", reflect.TypeOf((*MockJobRunInfo)(nil).IsFinished), ctx)
}

// SetGCSProwJobPath mocks base method.
func (m *MockJobRunInfo) SetGCSProwJobPath(gcsProwJobPath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGCSProwJobPath", gcsProwJobPath)
}

// SetGCSProwJobPath indicates an expected call of SetGCSProwJobPath.
func (mr *MockJobRunInfoMockRecorder) SetGCSProwJobPath(gcsProwJobPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGCSProwJobPath", reflect.TypeOf((*MockJobRunInfo)(nil).SetGCSProwJobPath), gcsProwJobPath)
}

// WriteCache mocks base method.
func (m *MockJobRunInfo) WriteCache(ctx context.Context, parentDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCache", ctx, parentDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCache indicates an expected call of WriteCache.
func (mr *MockJobRunInfoMockRecorder) WriteCache(ctx, parentDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCache", reflect.TypeOf((*MockJobRunInfo)(nil).WriteCache), ctx, parentDir)
}
