#!/bin/bash
set -euo pipefail

OLD_VERSION="${1:-}"
NEW_VERSION="${2:-}"
RELEASE_REPO="${3:-}"

if [ -z "$OLD_VERSION" ] || [ -z "$NEW_VERSION" ] || [ -z "$RELEASE_REPO" ]; then
    echo "Usage: $0 <old_version> <new_version> <release_repo>"
    echo "Example: $0 4.21 4.22 /path/to/release"
    exit 1
fi

echo "=========================================="
echo "Creating Pre-Branching Commits"
echo "=========================================="
echo ""
echo "Old version: $OLD_VERSION"
echo "New version: $NEW_VERSION"
echo "Release repo: $RELEASE_REPO"
echo ""

cd "$RELEASE_REPO"

# Check if there are changes to commit
if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
    echo "No changes to commit!"
    exit 1
fi

echo "=== Commit 1: Bump release gating jobs from Sippy ==="
echo ""

# Stage only CI operator config changes
git add ci-operator/config/

# Check if there are staged changes
if git diff --cached --quiet; then
    echo "No CI operator config changes to commit"
else
    git commit -m "bump release gating jobs from Sippy

Generated by:
./generated-release-gating-jobs --current-release=${OLD_VERSION} --release-repo=${RELEASE_REPO} --sippy-config=/tmp/sippy-openshift.yaml --interval=168"
    echo "✓ Commit 1 created"
fi

echo ""
echo "=== Commit 2: Release-controller configurations ==="
echo ""

# Stage release-controller configuration files
git add core-services/release-controller/_releases/

# Check if there are staged changes
if git diff --cached --quiet; then
    echo "No release-controller config changes to commit"
else
    git commit -m "release-controller ${NEW_VERSION} configuration

Created new release-controller configurations for ${NEW_VERSION} by copying from ${OLD_VERSION}."
    echo "✓ Commit 2 created"
fi

echo ""
echo "=== Commit 3: Add manual jobs and regenerate ==="
echo ""

# Stage all Prow job changes
git add ci-operator/jobs/

# Check if there are staged changes
if git diff --cached --quiet; then
    echo "No Prow job changes to commit"
else
    git commit -m "add manual jobs + make jobs

- Added standalone job definitions for ${NEW_VERSION} (install-analysis, upgrade-analysis, overall-analysis)
- Regenerated Prow jobs with 'make jobs'"
    echo "✓ Commit 3 created"
fi

echo ""
echo "=========================================="
echo "✓ All commits created!"
echo "=========================================="
echo ""
echo "Recent commits:"
git log --oneline -3
echo ""
echo "Next steps:"
echo "1. Review commits: git log -3 -p"
echo "2. Push to your fork: git push --set-upstream origin <branch-name>"
echo "3. Create a pull request"
