---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    # if instance type is unknown, so the autoscaler must be told about capacity:  https://access.redhat.com/solutions/6640721
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "32768"
    machine.openshift.io/vCPU: "32"
  labels:
    machine.openshift.io/cluster-api-cluster: build04-c92hb
  name: build04-c92hb-ci-tests-worker-b
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: build04-c92hb
      machine.openshift.io/cluster-api-machineset: build04-c92hb-ci-tests-worker-b
  template:
    metadata:
      annotations:
        # By the time we delete a machine, there should be nothing we care about.
        # The only times this is violated is pods in weird states. Ignore them.
        # https://github.com/openshift/machine-api-operator/blob/master/FAQ.md#i-want-to-skip-draining-when-i-delete-a-machine
        machine.openshift.io/exclude-node-draining: "true"
      labels:
        machine.openshift.io/cluster-api-cluster: build04-c92hb
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: build04-c92hb-ci-tests-worker-b
    spec:
      metadata:
        labels:
          ci-workload: tests
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          canIPForward: false
          credentialsSecret:
            name: gcp-cloud-credentials
          deletionProtection: false
          disks:
          - autoDelete: true
            boot: true
            image: projects/rhcos-cloud/global/images/rhcos-49-84-202110081407-0-gcp-x86-64
            sizeGb: 256
            type: pd-ssd
          kind: GCPMachineProviderSpec
          machineType: n1-highcpu-32
          metadata: {}
          networkInterfaces:
          - network: build04-c92hb-network
            subnetwork: build04-c92hb-worker-subnet
          projectID: openshift-ci-build-farm
          region: us-east1
          serviceAccounts:
          - email: build04-c92hb-w@openshift-ci-build-farm.iam.gserviceaccount.com
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
          tags:
          - build04-c92hb-worker
          userDataSecret:
            name: worker-user-data
          zone: us-east1-b
      taints:
      - effect: NoSchedule
        key: node-role.kubernetes.io/ci-tests-worker
        value: ci-tests-worker
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: build04-c92hb-ci-tests-worker-b
  namespace: openshift-machine-api
spec:
  maxReplicas: 120
  minReplicas: 0
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: build04-c92hb-ci-tests-worker-b