// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/secrets/client.go
//
// Generated by this command:
//
//	mockgen -source=pkg/secrets/client.go -destination=pkg/secrets/client_mock.go -package=secrets
//

// Package secrets is a generated GoMock package.
package secrets

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	types "k8s.io/apimachinery/pkg/types"
	sets "k8s.io/apimachinery/pkg/util/sets"
)

// MockReadOnlyClient is a mock of ReadOnlyClient interface.
type MockReadOnlyClient struct {
	ctrl     *gomock.Controller
	recorder *MockReadOnlyClientMockRecorder
	isgomock struct{}
}

// MockReadOnlyClientMockRecorder is the mock recorder for MockReadOnlyClient.
type MockReadOnlyClientMockRecorder struct {
	mock *MockReadOnlyClient
}

// NewMockReadOnlyClient creates a new mock instance.
func NewMockReadOnlyClient(ctrl *gomock.Controller) *MockReadOnlyClient {
	mock := &MockReadOnlyClient{ctrl: ctrl}
	mock.recorder = &MockReadOnlyClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadOnlyClient) EXPECT() *MockReadOnlyClientMockRecorder {
	return m.recorder
}

// GetFieldOnItem mocks base method.
func (m *MockReadOnlyClient) GetFieldOnItem(itemName, fieldName string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFieldOnItem", itemName, fieldName)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFieldOnItem indicates an expected call of GetFieldOnItem.
func (mr *MockReadOnlyClientMockRecorder) GetFieldOnItem(itemName, fieldName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldOnItem", reflect.TypeOf((*MockReadOnlyClient)(nil).GetFieldOnItem), itemName, fieldName)
}

// GetInUseInformationForAllItems mocks base method.
func (m *MockReadOnlyClient) GetInUseInformationForAllItems(optionalPrefix string) (map[string]SecretUsageComparer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInUseInformationForAllItems", optionalPrefix)
	ret0, _ := ret[0].(map[string]SecretUsageComparer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInUseInformationForAllItems indicates an expected call of GetInUseInformationForAllItems.
func (mr *MockReadOnlyClientMockRecorder) GetInUseInformationForAllItems(optionalPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInUseInformationForAllItems", reflect.TypeOf((*MockReadOnlyClient)(nil).GetInUseInformationForAllItems), optionalPrefix)
}

// GetUserSecrets mocks base method.
func (m *MockReadOnlyClient) GetUserSecrets() (map[types.NamespacedName]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSecrets")
	ret0, _ := ret[0].(map[types.NamespacedName]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSecrets indicates an expected call of GetUserSecrets.
func (mr *MockReadOnlyClientMockRecorder) GetUserSecrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSecrets", reflect.TypeOf((*MockReadOnlyClient)(nil).GetUserSecrets))
}

// HasItem mocks base method.
func (m *MockReadOnlyClient) HasItem(itemname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasItem", itemname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasItem indicates an expected call of HasItem.
func (mr *MockReadOnlyClientMockRecorder) HasItem(itemname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasItem", reflect.TypeOf((*MockReadOnlyClient)(nil).HasItem), itemname)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetFieldOnItem mocks base method.
func (m *MockClient) GetFieldOnItem(itemName, fieldName string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFieldOnItem", itemName, fieldName)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFieldOnItem indicates an expected call of GetFieldOnItem.
func (mr *MockClientMockRecorder) GetFieldOnItem(itemName, fieldName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFieldOnItem", reflect.TypeOf((*MockClient)(nil).GetFieldOnItem), itemName, fieldName)
}

// GetInUseInformationForAllItems mocks base method.
func (m *MockClient) GetInUseInformationForAllItems(optionalPrefix string) (map[string]SecretUsageComparer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInUseInformationForAllItems", optionalPrefix)
	ret0, _ := ret[0].(map[string]SecretUsageComparer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInUseInformationForAllItems indicates an expected call of GetInUseInformationForAllItems.
func (mr *MockClientMockRecorder) GetInUseInformationForAllItems(optionalPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInUseInformationForAllItems", reflect.TypeOf((*MockClient)(nil).GetInUseInformationForAllItems), optionalPrefix)
}

// GetUserSecrets mocks base method.
func (m *MockClient) GetUserSecrets() (map[types.NamespacedName]map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSecrets")
	ret0, _ := ret[0].(map[types.NamespacedName]map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSecrets indicates an expected call of GetUserSecrets.
func (mr *MockClientMockRecorder) GetUserSecrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSecrets", reflect.TypeOf((*MockClient)(nil).GetUserSecrets))
}

// HasItem mocks base method.
func (m *MockClient) HasItem(itemname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasItem", itemname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasItem indicates an expected call of HasItem.
func (mr *MockClientMockRecorder) HasItem(itemname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasItem", reflect.TypeOf((*MockClient)(nil).HasItem), itemname)
}

// SetFieldOnItem mocks base method.
func (m *MockClient) SetFieldOnItem(itemName, fieldName string, fieldValue []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFieldOnItem", itemName, fieldName, fieldValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFieldOnItem indicates an expected call of SetFieldOnItem.
func (mr *MockClientMockRecorder) SetFieldOnItem(itemName, fieldName, fieldValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFieldOnItem", reflect.TypeOf((*MockClient)(nil).SetFieldOnItem), itemName, fieldName, fieldValue)
}

// UpdateIndexSecret mocks base method.
func (m *MockClient) UpdateIndexSecret(itemName string, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIndexSecret", itemName, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIndexSecret indicates an expected call of UpdateIndexSecret.
func (mr *MockClientMockRecorder) UpdateIndexSecret(itemName, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIndexSecret", reflect.TypeOf((*MockClient)(nil).UpdateIndexSecret), itemName, payload)
}

// UpdateNotesOnItem mocks base method.
func (m *MockClient) UpdateNotesOnItem(itemName, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotesOnItem", itemName, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotesOnItem indicates an expected call of UpdateNotesOnItem.
func (mr *MockClientMockRecorder) UpdateNotesOnItem(itemName, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotesOnItem", reflect.TypeOf((*MockClient)(nil).UpdateNotesOnItem), itemName, notes)
}

// MockSecretUsageComparer is a mock of SecretUsageComparer interface.
type MockSecretUsageComparer struct {
	ctrl     *gomock.Controller
	recorder *MockSecretUsageComparerMockRecorder
	isgomock struct{}
}

// MockSecretUsageComparerMockRecorder is the mock recorder for MockSecretUsageComparer.
type MockSecretUsageComparerMockRecorder struct {
	mock *MockSecretUsageComparer
}

// NewMockSecretUsageComparer creates a new mock instance.
func NewMockSecretUsageComparer(ctrl *gomock.Controller) *MockSecretUsageComparer {
	mock := &MockSecretUsageComparer{ctrl: ctrl}
	mock.recorder = &MockSecretUsageComparerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretUsageComparer) EXPECT() *MockSecretUsageComparerMockRecorder {
	return m.recorder
}

// LastChanged mocks base method.
func (m *MockSecretUsageComparer) LastChanged() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastChanged")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// LastChanged indicates an expected call of LastChanged.
func (mr *MockSecretUsageComparerMockRecorder) LastChanged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastChanged", reflect.TypeOf((*MockSecretUsageComparer)(nil).LastChanged))
}

// SuperfluousFields mocks base method.
func (m *MockSecretUsageComparer) SuperfluousFields() sets.Set[string] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuperfluousFields")
	ret0, _ := ret[0].(sets.Set[string])
	return ret0
}

// SuperfluousFields indicates an expected call of SuperfluousFields.
func (mr *MockSecretUsageComparerMockRecorder) SuperfluousFields() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuperfluousFields", reflect.TypeOf((*MockSecretUsageComparer)(nil).SuperfluousFields))
}

// UnusedFields mocks base method.
func (m *MockSecretUsageComparer) UnusedFields(inUse sets.Set[string]) sets.Set[string] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnusedFields", inUse)
	ret0, _ := ret[0].(sets.Set[string])
	return ret0
}

// UnusedFields indicates an expected call of UnusedFields.
func (mr *MockSecretUsageComparerMockRecorder) UnusedFields(inUse any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnusedFields", reflect.TypeOf((*MockSecretUsageComparer)(nil).UnusedFields), inUse)
}
