package enhancement

import (
	"testing"

	jiraapi "github.com/andygrunwald/go-jira"
	"github.com/slack-go/slack"

	"github.com/openshift/ci-tools/pkg/jira"
	"github.com/openshift/ci-tools/pkg/slack/modals"
	"github.com/openshift/ci-tools/pkg/slack/modals/modaltesting"
)

func TestProcessSubmissionHandler(t *testing.T) {
	happyPath := modaltesting.SubmissionTestCase{
		Name: "happy path with additional details",
		Filer: jira.NewFake(map[jira.IssueRequest]jira.IssueResponse{
			{
				IssueType: "Story",
				Title:     "I Need Something",
				Description: `h3. Overview
As a person
I want to fly
So that I can be cool

h3. Summary
This is really important for me.

h3. Impact
Only I benefit.

h3. Acceptance Criteria
* I can fly
* Nobody else can fly

h3. Implementation Details
It needs to be done quickly.`,
				Reporter: "U01B31ARZDG",
			}: {
				Issue: &jiraapi.Issue{Key: "WHOA-123"},
				Error: nil,
			},
		}),
		Updater: modals.NewFake([]modals.ViewUpdate{
			{
				ViewUpdateRequest: modals.ViewUpdateRequest{
					View:       modals.JiraView("WHOA-123"),
					ExternalID: "",
					Hash:       "", // updated unconditionally, should be empty
					ViewID:     "V01C8N3BWAJ",
				},
				ViewUpdateResponse: modals.ViewUpdateResponse{
					Response: &slack.ViewResponse{},
					Error:    nil,
				},
			},
		}),
		ExpectedPayload: []byte(`{"response_action":"update","view":{"type":"modal","title":{"type":"plain_text","text":"Creating Jira Issue..."},"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"A Jira issue is being filed, please do not close this window..."}}],"private_metadata":"jira_pending"}}`),
		ExpectedError:   false,
	}
	modaltesting.ValidateSubmission(t, processSubmissionHandler(happyPath.Filer, happyPath.Updater), happyPath)
}

func TestIssueParameters(t *testing.T) {
	parameters := issueParameters()
	modaltesting.ValidateBlockIds(t, View(), parameters.Fields...)
	modaltesting.ValidateParameterProcessing(t, parameters, []modaltesting.ProcessTestCase{
		{
			Name:          "one acceptance criteria, no additional details",
			ExpectedTitle: "New Feature",
			ExpectedBody: `h3. Overview
As a developer
I want to have my code autogenerated
So that I can play World of Warcraft

h3. Summary
This will be a breakthrough for the company.

h3. Impact
Every developer can benefit.

h3. Acceptance Criteria
* I play ten hours of World Of Warcraft and do no work every day`,
		},
		{
			Name:          "many acceptance criteria, additional details",
			ExpectedTitle: "I Need Something",
			ExpectedBody: `h3. Overview
As a person
I want to fly
So that I can be cool

h3. Summary
This is really important for me.

h3. Impact
Only I benefit.

h3. Acceptance Criteria
* I can fly
* Nobody else can fly

h3. Implementation Details
It needs to be done quickly.`,
		},
	})
}
